TRAIN =  "./Input/Train.csv"
TEST = "./Input/Test.csv"
PREPROCESSED_TRAIN_FILE = "./Input/preprocessed_train_data.csv"
PREPROCESSED_TEST_FILE = "./Input/preprocessed_test_data.csv"
SUBMISSION = "./Input/SampleSubmission.csv"